# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - "master" # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - uses: actions/download-artifact@v3
        with:
          name: bundled-dist
          path: dist
      - run: npm run build-storybook-docs
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
